title: Big Brooklyn
description: Cybersecurity Blog + Portfolio
url: "https://whoistob1as.me"
baseurl: ""

theme: minima

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html

author:
  name: Tobias Arevalo
  email: heyyou@protonmail.com

show_drafts: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag