title: Tobias Guta Portfolio
description: Cybersecurity portfolio, projects, writeups, bug bounty notes, CTF walkthroughs, pentesting labs, and research.
url: "https://whoistob1as.me"
baseurl: ""

markdown: kramdown
future: false
permalink: /blog/:title/

exclude:
  - private_posts/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

giscus:
  enabled: true
  repo: "tobiasGuta/tobiasGuta.github.io"
  repo_id: "R_kgDOOxswYQ"
  category: "General"
  category_id: "DIC_kwDOOxswYc4CrEhp"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "transparent_dark"
  lang: "en"
